const API_URL = "https://script.google.com/macros/s/AKfycbzcifHldn8TgviYzgvqG5a7XQctukxz8yMeitbdRnRI1SS4pxD1fOs5Wl5YAfxN-EVZ/exec";

const pizzas = [
    { id: 1, nome: "Alho", categoria: "salgada", ingredientes: "alho crocante, muçarela, parmesão", preco: { BROTO: 45.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 2, nome: "Aliche Argentino", categoria: "salgada", ingredientes: "filés de anchovas, muçarela, tomate, parmesão", preco: { BROTO: 55.00, MÉDIA: 65.00, GRANDE: 75.00, FAMÍLIA: 85.00 } },
    { id: 3, nome: "Americana", categoria: "salgada", ingredientes: "muçarela, presunto cozido, azeitonas picadas", preco: { BROTO: 43.00, MÉDIA: 54.00, GRANDE: 64.00, FAMÍLIA: 74.00 } },
    { id: 4, nome: "A Moda da Casa", categoria: "salgada", ingredientes: "atum sólido em pedaços, muçarela, ervilha fresca, cebola, bacon", preco: { BROTO: 52.00, MÉDIA: 65.00, GRANDE: 75.00, FAMÍLIA: 85.00 } },
    { id: 5, nome: "Argentina",categoria: "salgada", ingredientes: "atum sólido em pedaços, provolone, cebola", preco: { BROTO: 52.00, MÉDIA: 63.00, GRANDE: 74.00, FAMÍLIA: 84.00 } },
    { id: 6, nome: "Atum Sólido",categoria: "salgada", ingredientes: "atum sólido em pedaços, cebola", preco: { BROTO: 48.00, MÉDIA: 58.00, GRANDE: 69.00, FAMÍLIA: 79.00 } },
    { id: 7, nome: "Bacon",categoria: "salgada",ingredientes: "muçarela, bacon, ovos", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 66.00, FAMÍLIA: 76.00 } },
    { id: 8, nome: "Baiacatu",categoria: "salgada", ingredientes: "calabresa moída, catupiry, cebola", preco: { BROTO: 44.00, MÉDIA: 56.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 9, nome: "Baiana", categoria: "salgada",ingredientes: "calabresa moída, pimenta, cebola, ovos", preco: { BROTO: 40.00, MÉDIA: 50.00, GRANDE: 57.90, FAMÍLIA: 67.90 } },
    { id: 10, nome: "Baiana 2", categoria: "salgada",ingredientes: "calabresa moída, muçarela, pimenta, parmesão", preco: { BROTO: 44.00, MÉDIA: 56.00, GRANDE: 66.00, FAMÍLIA: 76.00 } },
    { id: 11, nome: "Berinjela",categoria: "salgada", ingredientes: "berinjela refogada no azeite, muçarela, cebola", preco: { BROTO: 42.00, MÉDIA: 52.00, GRANDE: 62.00, FAMÍLIA: 72.00 } },
    { id: 12, nome: "Brasileira",categoria: "salgada", ingredientes: "atum sólido em pedaços, muçarela, cebola", preco: { BROTO: 52.00, MÉDIA: 64.00, GRANDE: 74.00, FAMÍLIA: 84.00 } },
    { id: 13, nome: "Brasileira 2", categoria: "salgada",ingredientes: "atum sólido em pedaços, catupiry, cebola", preco: { BROTO: 55.00, MÉDIA: 66.00, GRANDE: 78.00, FAMÍLIA: 88.00 } },
    { id: 14, nome: "Brócolis", categoria: "salgada",ingredientes: "brócolis refogado no azeite, muçarela", preco: { BROTO: 43.00, MÉDIA: 54.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 15, nome: "Caipira", categoria: "salgada",ingredientes: "peito de frango desfiado, milho, catupiry", preco: { BROTO: 45.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 16, nome: "Calabresa", categoria: "salgada",ingredientes: "calabresa fatiada, cebola", preco: { BROTO: 40.00, MÉDIA: 50.00, GRANDE: 57.90, FAMÍLIA: 67.90 } },
    { id: 17, nome: "Camarão", categoria: "salgada",ingredientes: "camarão graúdo refogado no azeite, catupiry original", preco: { BROTO: 55.00, MÉDIA: 65.00, GRANDE: 85.00, FAMÍLIA: 95.00 } },
    { id: 18, nome: "Canadense", categoria: "salgada",ingredientes: "lombo canadense, cebola, catupiry", preco: { BROTO: 46.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 19, nome: "Carbonara", categoria: "salgada",ingredientes: "calabresa fatiada, champignon, muçarela, ervilha fresca, ovos", preco: { BROTO: 46.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 20, nome: "Carne Seca", categoria: "salgada",ingredientes: "carne seca refogada, muçarela, cebola", preco: { BROTO: 48.00, MÉDIA: 60.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 21, nome: "Carne Seca 2", categoria: "salgada",ingredientes: "carne seca refogada, catupiry, cebola", preco: { BROTO: 49.00, MÉDIA: 61.00, GRANDE: 71.00, FAMÍLIA: 81.00 } },
    { id: 22, nome: "Catumilho", categoria: "salgada",ingredientes: "catupiry, milho", preco: { BROTO: 44.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 23, nome: "Catupiry", categoria: "salgada",ingredientes: "catupiry, tomate fatiado", preco: { BROTO: 45.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 24, nome: "Crocante", categoria: "salgada",ingredientes: "muçarela, batata palha crocante", preco: { BROTO: 43.00, MÉDIA: 53.00, GRANDE: 63.00, FAMÍLIA: 73.00 } },
    { id: 25, nome: "Dois Queijos", categoria: "salgada",ingredientes: "muçarela, catupiry", preco: { BROTO: 44.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 26, nome: "Escarola", categoria: "salgada",ingredientes: "escarola refogada no azeite, muçarela, cebola", preco: { BROTO: 42.00, MÉDIA: 52.00, GRANDE: 62.00, FAMÍLIA: 72.00 } },
    { id: 27, nome: "Escarola 2", categoria: "salgada",ingredientes: "escarola refogada no azeite, bacon, muçarela", preco: { BROTO: 45.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 28, nome: "Francesa", categoria: "salgada",ingredientes: "presunto cozido, bacon, catupiry", preco: { BROTO: 43.00, MÉDIA: 56.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 29, nome: "Frangalho", categoria: "salgada",ingredientes: "frango desfiado, muçarela, alho crocante", preco: { BROTO: 43.00, MÉDIA: 56.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 30, nome: "Galeto", categoria: "salgada",ingredientes: "frango desfiado, milho, tomate, queijo cheddar", preco: { BROTO: 46.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 31, nome: "Jardineira", categoria: "salgada",ingredientes: "peito de peru defumado, palmito, milho, ervilha, champignon e catupiry", preco: { BROTO: 53.00, MÉDIA: 66.00, GRANDE: 76.00, FAMÍLIA: 86.00 } },
    { id: 32, nome: "Lombinho", categoria: "salgada",ingredientes: "lombo canadense e cebola", preco: { BROTO: 39.00, MÉDIA: 50.00, GRANDE: 60.00, FAMÍLIA: 70.00 } },
    { id: 33, nome: "Marguerita", categoria: "salgada",ingredientes: "muçarela, rodelas de tomate, manjericão fresco e parmesão", preco: { BROTO: 44.00, MÉDIA: 54.00, GRANDE: 64.00, FAMÍLIA: 74.00 } },
    { id: 34, nome: "Milho", categoria: "salgada",ingredientes: "milho e muçarela", preco: { BROTO: 43.00, MÉDIA: 54.00, GRANDE: 63.00, FAMÍLIA: 73.00 } },
    { id: 35, nome: "Muçarela de Búfala", categoria: "salgada",ingredientes: "muçarela de búfala e tomate seco", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 36, nome: "Muçarela", categoria: "salgada",ingredientes: "muçarela e azeitonas", preco: { BROTO: 40.00, MÉDIA: 50.00, GRANDE: 59.90, FAMÍLIA: 69.90 } },
    { id: 37, nome: "Napolitana", categoria: "salgada",ingredientes: "muçarela, parmesão e rodelas de tomate", preco: { BROTO: 44.00, MÉDIA: 54.00, GRANDE: 64.00, FAMÍLIA: 74.00 } },
    { id: 38, nome: "Palmito", categoria: "salgada",ingredientes: "palmito, muçarela e tomate", preco: { BROTO: 46.00, MÉDIA: 60.00, GRANDE: 70.00, FAMÍLIA: 80.00 } },
    { id: 39, nome: "Namorados", categoria: "salgada",ingredientes: "palmito, muçarela e catupiry", preco: { BROTO: 46.00, MÉDIA: 60.00, GRANDE: 70.00, FAMÍLIA: 80.00 } },
    { id: 40, nome: "Parisiense", categoria: "salgada",ingredientes: "frango desfiado, ervilha fresca, palmito e muçarela", preco: { BROTO: 46.00, MÉDIA: 59.00, GRANDE: 69.00, FAMÍLIA: 79.00 } },
    { id: 41, nome: "Peito de Peru", categoria: "salgada",ingredientes: "peito de peru defumado e catupiry", preco: { BROTO: 45.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 42, nome: "Peito de Peru 2", categoria: "salgada",ingredientes: "peito de peru defumado, tomate, muçarela e parmesão", preco: { BROTO: 45.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 43, nome: "Pepperoni", categoria: "salgada",ingredientes: "muçarela, pepperoni e parmesão", preco: { BROTO: 46.00, MÉDIA: 59.00, GRANDE: 69.00, FAMÍLIA: 79.00 } },
    { id: 44, nome: "Peruana", categoria: "salgada",ingredientes: "atum sólido em pedaços, palmito, catupiry e cebola", preco: { BROTO: 56.00, MÉDIA: 67.00, GRANDE: 80.00, FAMÍLIA: 90.00 } },
    { id: 45, nome: "Pizzaiolo", categoria: "salgada",ingredientes: "frango desfiado, palmito, ovos, bacon e catupiry", preco: { BROTO: 46.00, MÉDIA: 59.00, GRANDE: 69.00, FAMÍLIA: 79.00 } },
    { id: 46, nome: "Portuguesa", categoria: "salgada",ingredientes: "muçarela, presunto cozido, ovos, ervilha fresca e cebola", preco: { BROTO: 44.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 47, nome: "Quatro Queijos", categoria: "salgada",ingredientes: "muçarela, provolone, catupiry e gorgonzola", preco: { BROTO: 48.00, MÉDIA: 60.00, GRANDE: 70.00, FAMÍLIA: 80.00 } },
    { id: 48, nome: "Siciliana", categoria: "salgada",ingredientes: "champignon, muçarela, tomate e bacon", preco: { BROTO: 45.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 49, nome: "Toscana", categoria: "salgada",ingredientes: "calabresa fatiada e muçarela", preco: { BROTO: 44.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 50, nome: "Três Terços", categoria: "salgada",ingredientes: "três sabores de pizzas a sua escolha (exceto camarão e parma)", preco: { BROTO: 65.00, MÉDIA: 65.00, GRANDE: 75.00, FAMÍLIA: 85.00 } },
    { id: 51, nome: "Três Queijos", categoria: "salgada",ingredientes: "muçarela, provolone e catupiry", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 52, nome: "A Fornalha", categoria: "especial",ingredientes: "muçarela de búfala, peito de peru, tomate seco e batata palha", preco: { BROTO: 46.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 53, nome: "Brócolis Especial", categoria: "especial",ingredientes: "brócolis refogado no azeite, bacon e provolone", preco: { BROTO: 44.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 54, nome: "Cinco Queijos", categoria: "especial",ingredientes: "muçarela, provolone, parmesão, catupiry e gorgonzola", preco: { BROTO: 48.00, MÉDIA: 60.00, GRANDE: 70.00, FAMÍLIA: 80.00 } },
    { id: 55, nome: "Criativa", categoria: "especial",ngredientes: "monte sua pizza com até quatro ingredientes (exceto camarão e parma)", preco: { BROTO: 52.00, MÉDIA: 62.00, GRANDE: 72.00, FAMÍLIA: 82.00 } },
    { id: 56, nome: "Escarola Especial", categoria: "especial",ingredientes: "escarola refogada no azeite, bacon, champignon e catupiry", preco: { BROTO: 45.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 57, nome: "Portuguesa Especial", categoria: "especial",ingredientes: "muçarela, presunto cozido, ovos, cebola, palmito e ervilha fresca", preco: { BROTO: 46.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 58, nome: "Tropical", categoria: "especial",ingredientes: "lombo canadense, muçarela e abacaxi", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 59, nome: "Rúcula", categoria: "especial",ingredientes: "rúcula hidropônica, tomate seco e muçarela de búfala", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 60, nome: "Toronto", categoria: "especial",ingredientes: "lombo canadense, cebola, ovos e provolone", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 61, nome: "Vegetariana", categoria: "especial",ingredientes: "palmito, escarola, cebola, milho, ervilha, tomate seco e muçarela", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 62, nome: "Bolonhesa", categoria: "especial",ingredientes: "carne moída refogada, muçarela e catupiry", preco: { BROTO: 52.00, MÉDIA: 62.00, GRANDE: 72.00, FAMÍLIA: 82.00 } },
    { id: 63, nome: "Estrogonofe", categoria: "especial",ingredientes: "carne em tiras, muçarela, champignon, parmesão e batata palha crocante", preco: { BROTO: 52.00, MÉDIA: 62.00, GRANDE: 72.00, FAMÍLIA: 82.00 } },
    { id: 107, nome: "Hot Dog", categoria: "especial",ingredientes: "salsicha fatiada, rodelas de tomate, cebola, muçarela e batata palha", preco: { BROTO: 45.00, MÉDIA: 57.00, GRANDE: 67.00, FAMÍLIA: 77.00 } },
    { id: 108, nome: "Hamburguer Picanha", categoria: "especial",ingredientes: "hamburguer de picanha, muçarela, tomate e alface", preco: { BROTO: 45.00, MÉDIA: 55.00, GRANDE: 65.00, FAMÍLIA: 75.00 } },
    { id: 110, nome: "Lombo Especial", categoria: "especial",ingredientes: "lombo canadense, cream cheese e bacon em cubos", preco: { BROTO: 45.00, MÉDIA: 58.00, GRANDE: 68.00, FAMÍLIA: 78.00 } },
    { id: 111, nome: "Coração Alcachofra", categoria: "especial",ingredientes: "alcachofra, muçarela de búfala, manjericão fresco e azeitonas pretas fatiadas", preco: { BROTO: 52.00, MÉDIA: 64.00, GRANDE: 74.00, FAMÍLIA: 84.00 } },
    { id: 112, nome: "Presunto Parma", categoria: "especial",ingredientes: "parma, coração de alcachofra, muçarela de búfala, manjericão e azeitonas pretas fatiadas", preco: { BROTO: 55.00, MÉDIA: 68.00, GRANDE: 82.00, FAMÍLIA: 92.00 } },
    { id: 113, nome: "Alho Negro", categoria: "especial",ingredientes: "muçarela, tomate cereja e alho negro em pasta", preco: { BROTO: 52.00, MÉDIA: 62.00, GRANDE: 72.00, FAMÍLIA: 82.00 } },
    { id: 101, nome: "Tarantela (Light)", categoria: "Light",ingredientes: "queijo fresco, rúcula hidropônica e tomate seco", preco: { BROTO: 36.00, MÉDIA: 46.00, GRANDE: 56.00, FAMÍLIA: 66.00 } },
    { id: 102, nome: "Banana (Doce)", categoria: "doce",ingredientes: "banana, canela e leite condensado", preco: { BROTO: 38.00, MÉDIA: 45.00, GRANDE: 49.00, FAMÍLIA: 59.00 } },
    { id: 103, nome: "Romeu e Julieta", categoria: "doce",ingredientes: "muçarela e goiabada cremosa", preco: { BROTO: 38.00, MÉDIA: 45.00, GRANDE: 49.00, FAMÍLIA: 59.00 } },
    { id: 104, nome: "Sensação", categoria: "doce",ingredientes: "chocolate ao leite, morangos e leite condensado", preco: { BROTO: 38.00, MÉDIA: 45.00, GRANDE: 49.00, FAMÍLIA: 59.00 } },
    { id: 105, nome: "Floresta Negra", categoria: "doce",ingredientes: "chocolate ao leite, granulado de chocolate e cereja ao marasquino", preco: { BROTO: 38.00, MÉDIA: 45.00, GRANDE: 49.00, FAMÍLIA: 59.00 } },
    { id: 106, nome: "Casal 20", categoria: "doce",ingredientes: "chocolate branco, chocolate ao leite e morangos (ou produtos da época)", preco: { BROTO: 38.00, MÉDIA: 45.00, GRANDE: 49.00, FAMÍLIA: 59.00 } },
    { id: 109, nome: "M&M's", categoria: "doce",ingredientes: "chocolate ao leite e confeitos coloridos", preco: { BROTO: 38.00, MÉDIA: 45.00, GRANDE: 49.00, FAMÍLIA: 59.00 } },
    { id: 120, nome: "Churros", categoria: "doce",ingredientes: "doce de leite, granulado e canela", preco: { BROTO: 38.00, MÉDIA: 45.00, GRANDE: 49.00, FAMÍLIA: 59.00 } }
]

const bebidas = [
    { id: 1001, categoria: "nao_alcoolica",nome: "Coca-Cola 2L", preco: 17.00 },
    { id: 1002, categoria: "nao_alcoolica",nome: "Coca-Cola Zero 2L", preco: 17.00 },
    { id: 1003, categoria: "nao_alcoolica",nome: "Sprite 2L", preco: 15.00 },
    { id: 1004, categoria: "nao_alcoolica",nome: "Fanta Laranja 2L", preco: 15.00 },
    { id: 1005, categoria: "nao_alcoolica",nome: "Fanta Uva 2L", preco: 15.00 },
    { id: 1006, categoria: "nao_alcoolica",nome: "Fanta Guaraná 2L", preco: 15.00 },
    { id: 1007, categoria: "nao_alcoolica",nome: "Sucos 1L", preco: 8.50 },
    { id: 1008, categoria: "nao_alcoolica",nome: "Coca-Cola 600ml", preco: 10.00 },
    { id: 1009, categoria: "nao_alcoolica",nome: "Refrigerante 600ml (Outros)", preco: 10.00 },
    { id: 1010, categoria: "nao_alcoolica",nome: "Refrigerante em lata", preco: 6.00 },
    { id: 1011, categoria: "nao_alcoolica",nome: "Água sem gás 500ml", preco: 4.00 },
    { id: 1012, categoria: "nao_alcoolica",nome: "Água com gás 500ml", preco: 4.00 },
    { id: 1013, categoria: "alcoolica",nome: "Cerveja Budweiser", preco: 12.00 },
    { id: 1014, categoria: "alcoolica",nome: "Cerveja Eisenbahn", preco: 12.00 },
    { id: 1015, categoria: "alcoolica",nome: "Cerveja Stella Artois", preco: 12.00 },
    { id: 1016, categoria: "alcoolica",nome: "Cerveja Heineken", preco: 12.00 },
    { id: 1017, categoria: "alcoolica",nome: "Vinho da Casa (Seco)", preco: 25.00 },
    { id: 1018, categoria: "alcoolica",nome: "Vinho da Casa (Suave)", preco: 25.00 }
];

function formatarMoeda(valor) {
    return valor.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}